config/routes.rb
Rails.application.routes.draw do

  root to: "albums#index"

  resources :albums

  post 'albums/create-images', to: 'images#create'

  get 'albums/show-images/:id', to: 'albums#show_images', as: 'show_images'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  before_validation :assign_prefix, on: :create
  validates_presence_of :name, :prefix
  has_many :images, foreign_key: :album_prefix, primary_key: :prefix

  def assign_prefix
    self.prefix = SecureRandom.hex(4)
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  validates_presence_of :name, :album_prefix, :extension
  belongs_to :album, foreign_key: :album_prefix, primary_key: :prefix


  def extension_format
    if self.extension.blank? || (self.extension.strip.downcase =~ /\A(jpg|jpeg|png)\z/).blank?
      self.errors.add(:base, "Only jpg, jpeg, png extensions are allowed")
    end
  end

  def generate_version_url(version)
    return  Config::VERSION_IMAGES_BASE_URL + Config::VERSION_IMAGES_BUCKET + "/#{self.album_prefix}/#{self.name}/#{version}.#{self.extension}"
  end

end
  

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :show_images]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end


  def show_images
    @gallery_images = @album.images.map{|x| x.generate_version_url('large')}
    render "show_images"
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :prefix)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout "application"
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def create
    _, bucket, prefix, file_name, version = URI.decode(params["filepath"]).split("/")
    version_name, extension = version.split(".")
    image = Image.new({album_prefix: prefix, name: file_name, extension: extension})
    if image.save
      status, message = 200, nil, "Successfully Saved"
    else
      status, message =  400, image.errors.full_messages
    end
    render json: {message: message}, status: status
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Name</p>
  <div class="field">
    <%= form.text_field :name, id: :album_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Prefix</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.name %></td>
        <td><%= album.prefix %></td>
        <td ><%= link_to 'Add Images', album %></td>
        <td ><%= link_to 'Show Images', show_images_path(album) %></td>

      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'Create New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<%= link_to 'Back', albums_path %>

<p id="notice"><%= notice %></p>

<h2> Album <%= "#{@album.name}" %></h2>

<div style="margin-top: 30px">
  <p> Add new images</p>
  <%= s3_uploader_form callback_url: "create-images",
                     callback_method: "POST",
                     callback_param: "image_url",
                     key: "#{@album.prefix}/{timestamp}-{unique_id}/original.{extension}",
                     key_starts_with: "#{@album.prefix}",
                     acl: "public-read",
                     max_file_size: 50.megabytes,
                     id: "myS3Uploader",
                     class: "upload-form" do %>
  <%= file_field_tag :file, multiple: true %>
<% end %>
</div>

<br>
<br>

<table>
   <tbody>
    <tr>
      <td>Existing Images:</td>
      <td><%= @album.images.count %> </td>
    </tr>
  </tbody>


   <tbody>
    <tr>
       <td><%= link_to 'Show Images', show_images_path(@album) %></td>
    </tr>
  </tbody>

</table>


<script type="text/javascript">

  $(document).ready(function () {
   $("#myS3Uploader").S3Uploader();

  $('#myS3Uploader').bind('s3_uploads_start', function() {
    console.log("Uploads have started")
  });

  $('#myS3Uploader').bind("s3_upload_complete", function(e, content){
    //alert(content.url)
  });
  
  $(document).bind('s3_uploads_complete', function() {
    if(typeof flag == "undefined"){
       alert("All Uploads completed") 
    }
    flag = true
  });

  $('#myS3Uploader').bind("ajax:success", function(e, data){
    console.log("server was successfully notified of new file on S3")
  });

   $('#myS3Uploader').bind("ajax:error", function(e, data){
      alert("server was notified of new file on S3 responded with " + data['responseJSON']['message'].join(",") )
    });

  $('#myS3Uploader').bind("s3_upload_failed", function(e, content){
    alert( content.filename + "  failed to upload : " + content.error_thrown )
  });
});
  

  
</script>

<script id="template-upload" type="text/x-tmpl">
<div id="file-{%=o.unique_id%}" class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>

app/views/albums/show_images.html.erb
<head>
    <title>Gallery</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>


<%= link_to 'Back To Albums', albums_path %>
<% count = @gallery_images.count %>
<% unless count.zero? %>

        <body class="home">
        <div class="container" style="margin-top:40px;">
            <h2>Gallery</h2>
            <div class="demo-gallery">
                <ul class="list-unstyled row">
                    <% @gallery_images.each_with_index do |image_url, index| %>
                    <li class="col-xs-6 col-sm-4 col-md-2 col-lg-2" >
                        <a href=<%="#{image_url}"%> target="_blank">
                            <img class="img-responsive" src=<%="#{image_url}"%>>
                        </a>
                    </li>
                    <% end %>

                </ul>
            </div>
        </div>
    </body>   
<br>

<% else %>
    <h3>No images in Album</h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imageuploader</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>